language: python
python:
  - "2.7"
  - "pypy"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y liblzo2-2 liblzma5 liblua5.1-0
  - wget http://cdimage.debian.org/ubuntu/ubuntu/pool/universe/k/kyototycoon/kyototycoon_0.9.56-1_amd64.deb
  - wget http://cdimage.debian.org/ubuntu/ubuntu/pool/universe/k/kyototycoon/libkyototycoon2_0.9.56-1_amd64.deb
  - wget http://cdimage.debian.org/ubuntu/ubuntu/pool/universe/k/kyotocabinet/libkyotocabinet16_1.2.76-4_amd64.deb
  - sudo dpkg --force-depends -i libkyotocabinet16_1.2.76-4_amd64.deb
  - sudo dpkg -i libkyototycoon2_0.9.56-1_amd64.deb
  - sudo dpkg -i kyototycoon_0.9.56-1_amd64.deb
install:
  - pip install -e .[tests]
  - pip install pytest-cov flake8 coveralls
before_script:
  - ktserver -dmn '+' '-'
script:
  - py.test -vv --cov dongraetrader
  - flake8
after_success:
  - coveralls
